/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ContactSection = {
  _type: "contactSection";
  heading?: string;
  email?: string;
  offices?: Array<{
    _key: string;
  } & Office>;
  formHeading?: string;
};

export type InsightsGrid = {
  _type: "insightsGrid";
  heading?: string;
  featuredPosts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogPost";
  }>;
};

export type ProjectsShowcase = {
  _type: "projectsShowcase";
  heading?: string;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type ServicesShowcase = {
  _type: "servicesShowcase";
  heading?: string;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  cta?: Cta;
};

export type IntroSection = {
  _type: "introSection";
  heading?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  badge?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    text?: string;
  };
  cta?: Cta;
};

export type Hero = {
  _type: "hero";
  heading?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  theme?: "blue" | "dark" | "light";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<{
    _key: string;
  } & Hero | {
    _key: string;
  } & IntroSection | {
    _key: string;
  } & ServicesShowcase | {
    _key: string;
  } & ProjectsShowcase | {
    _key: string;
  } & InsightsGrid | {
    _key: string;
  } & ContactSection>;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type Cta = {
  _type: "cta";
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: string;
  externalUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  email?: string;
  offices?: Array<{
    _key: string;
  } & Office>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  footerColumns?: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  author?: string;
  publishedAt?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  description?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  url?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "technology" | "design";
  description?: string;
  items?: Array<string>;
};

export type Office = {
  _type: "office";
  city?: string;
  country?: string;
  address?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ContactSection | InsightsGrid | ProjectsShowcase | ServicesShowcase | IntroSection | Hero | Page | Cta | SanityImageCrop | SanityImageHotspot | Slug | SiteSettings | BlogPost | Project | Service | Office | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    slug,    seo,    pageBuilder[]{      ...,      _type == "servicesShowcase" => {        ...,        services[]->{          _id,          title,          category,          description,          items        }      },      _type == "projectsShowcase" => {        ...,        projects[]->{          _id,          title,          slug,          client,          description,          coverImage,          tags,          url        }      },      _type == "insightsGrid" => {        ...,        featuredPosts[]->{          _id,          title,          slug,          coverImage,          excerpt,          author,          publishedAt        }      }    }  }
export type PAGE_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  seo: {
    title?: string;
    description?: string;
  } | null;
  pageBuilder: Array<{
    _key: string;
    _type: "contactSection";
    heading?: string;
    email?: string;
    offices?: Array<{
      _key: string;
    } & Office>;
    formHeading?: string;
  } | {
    _key: string;
    _type: "hero";
    heading?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    theme?: "blue" | "dark" | "light";
  } | {
    _key: string;
    _type: "insightsGrid";
    heading?: string;
    featuredPosts: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      coverImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      excerpt: string | null;
      author: string | null;
      publishedAt: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "introSection";
    heading?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    description?: string;
    badge?: {
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      text?: string;
    };
    cta?: Cta;
  } | {
    _key: string;
    _type: "projectsShowcase";
    heading?: string;
    projects: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      client: string | null;
      description: string | null;
      coverImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      tags: Array<string> | null;
      url: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "servicesShowcase";
    heading?: string;
    services: Array<{
      _id: string;
      title: string | null;
      category: "design" | "technology" | null;
      description: string | null;
      items: Array<string> | null;
    }> | null;
    cta?: Cta;
  }> | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    _id,    companyName,    email,    offices,    socialLinks,    footerColumns  }
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  companyName: string | null;
  email: string | null;
  offices: Array<{
    _key: string;
  } & Office> | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
  footerColumns: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    seo,\n    pageBuilder[]{\n      ...,\n      _type == \"servicesShowcase\" => {\n        ...,\n        services[]->{\n          _id,\n          title,\n          category,\n          description,\n          items\n        }\n      },\n      _type == \"projectsShowcase\" => {\n        ...,\n        projects[]->{\n          _id,\n          title,\n          slug,\n          client,\n          description,\n          coverImage,\n          tags,\n          url\n        }\n      },\n      _type == \"insightsGrid\" => {\n        ...,\n        featuredPosts[]->{\n          _id,\n          title,\n          slug,\n          coverImage,\n          excerpt,\n          author,\n          publishedAt\n        }\n      }\n    }\n  }\n": PAGE_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0]{\n    _id,\n    companyName,\n    email,\n    offices,\n    socialLinks,\n    footerColumns\n  }\n": SITE_SETTINGS_QUERYResult;
  }
}
